version: '3.4'

services:
  hse.backend:
    image: nexus.aranuma.com:8889/stage.smarthse.back:latest
    container_name: stage_smarthse_backend
    restart: unless-stopped
    hostname: stage_smarthse
    environment:
      - ASPNETCORE_ENVIRONMENT=Stage
      - TZ=Asia/Tehran
    ports:
      - 6761:5000
    volumes:
      - /var/cdn/stage/Facedetection:/app/Facedetection
      - /var/cdn/stage/Smarthse:/app/Smarthse
      - /var/containers/BackHse/data/mongodata:/app/mongodata
      - /var/containers/BackHse/log:/Log
      - /var/containers/BackHse/conf:/app/Config
      - /var/containers/BackHse/cert/MqttCert:/app/MqttCert
      - /var/containers/BackHse/cert/MongoCert:/app/MongoCert

